### ISSUE TITLE
[Enhancement] Switch from identity

### ISSUE THREAD

**Issue by Tim-W** [worldsibu/convector-rest-api#18]
It would be very useful to be able to switch from identity for trying out REST endpoints from different authorizations. Currently, in `env.ts`, all values are defines as constants. But perhaps this could be done more dynamically, so that a single endpoint can be tested by a admin and a non-admin.

**Comment by bernardo9999** [comment]
env.ts specifically sets to admin if:

export const identityId = process.env.IDENTITYID || 'admin';
export const identityName = process.env.IDENTITY || 'admin';

So, it is dynamic from an external endpoint.
