### ISSUE TITLE
Property `type` should not be included in swagger

### ISSUE THREAD

**Issue by walmon** [worldsibu/convector-rest-api#2]
That prop is set by default in the Model, it shouldn't be passed as a param

**Comment by xcottos** [comment]
interesting, that implies I will create decorators also in the Models in order to include/exclude parameters from the code generation

**Comment by walmon** [comment]
Or maybe exclude `type` by default since it's a system property. Later we can introduce advanced granular setups like decorators in models :)

**Comment by xcottos** [comment]
yeah that will be the first and quick solution that at least allows ppl to use it without mistakes

**Comment by xcottos** [comment]
done
