### ISSUE TITLE
Controller doesn't compile chaincode model well (pascal case)

### ISSUE THREAD

**Issue by walmon** [worldsibu/convector-rest-api#4]
![image](https://user-images.githubusercontent.com/5282988/53295846-cc79cf80-37c9-11e9-9328-a8163d14a413.png)

`Property 'testchaincode' does not exist on type 'typeof Models'. Did you mean 'Testchaincode'`

It's because it's using a lowercase but the rest of the project uses PascalCase.

## Replicate

```
conv new tetproject -c testchaincode
cd tetproject
# Run convector-rest-api there
```

**Comment by xcottos** [comment]
I cannot replicate it, 

I just started from scratch new project and the generation/compilation works..

**Comment by xcottos** [comment]
I just verified that method created in my example (from scratch)

async create(req: Request, res: Response) {
    try {
      let cntrl = await MytestaController.init();
      let modelRaw = req.body;
      let model = **new Models.Mytesta(modelRaw);**
      await cntrl.create(model);
      res.send(201);
    } catch (ex) {
      console.log(ex.message, ex.stack);
      res.status(500).send(ex);
    }
  }

So it seems to work I am closing it by now, if you keep encountering it we investigate better
